import type { AssetIP, Creator, Collection } from "@/src/types/asset"

export const creators: Creator[] = [
  {
    id: "1",
    name: "Alex Chen",
    username: "alexchen",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: true,
    bio: "Digital artist and IP creator specializing in generative art and blockchain technology.",
    location: "San Francisco, CA",
    website: "https://alexchen.art",
    joinedDate: "2023-01-15",
    totalAssets: 24,
    totalCollections: 3,
    protectedAssets: 22,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    username: "sarahjohnson",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: true,
    bio: "Photographer and visual storyteller with a passion for capturing authentic moments.",
    location: "New York, NY",
    website: "https://sarahjohnson.photo",
    joinedDate: "2023-02-20",
    totalAssets: 18,
    totalCollections: 2,
    protectedAssets: 16,
  },
  {
    id: "3",
    name: "Marcus Rodriguez",
    username: "marcusrodriguez",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: false,
    bio: "Music producer and sound designer creating innovative audio experiences.",
    location: "Los Angeles, CA",
    website: "https://marcusrodriguez.music",
    joinedDate: "2023-03-10",
    totalAssets: 12,
    totalCollections: 1,
    protectedAssets: 10,
  },
]

export const timelineAssets: AssetIP[] = [
  {
    id: "1",
    title: "Quantum Dreams #001",
    slug: "quantum-dreams-001",
    description:
      "A mesmerizing digital artwork exploring the intersection of quantum physics and consciousness through vibrant colors and geometric patterns.",
    type: "Art",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Alex Chen",
    creator: creators[0],
    licenseType: "creative-commons",
    ipVersion: "1.0",
    registrationDate: "2024-01-15",
    timestamp: "2 hours ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x1a2b3c4d5e6f",
    fileFormat: "PNG",
    commercialUse: true,
    modifications: true,
    attribution: true,
    tags: "digital art, quantum, consciousness, geometric",
    externalUrl: "https://quantum-dreams.art",
    attributes: [
      { trait_type: "Style", value: "Abstract" },
      { trait_type: "Color Palette", value: "Vibrant" },
      { trait_type: "Complexity", value: "High" },
      { trait_type: "Medium", value: "Digital" },
    ],
  },
  {
    id: "2",
    title: "Urban Symphony",
    slug: "urban-symphony",
    description:
      "A captivating photograph capturing the rhythm and energy of city life through architectural lines and human movement.",
    type: "Image",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Sarah Johnson",
    creator: creators[1],
    licenseType: "all-rights",
    ipVersion: "1.2",
    registrationDate: "2024-01-14",
    timestamp: "5 hours ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x2b3c4d5e6f7a",
    fileFormat: "JPEG",
    commercialUse: false,
    modifications: false,
    attribution: true,
    tags: "photography, urban, architecture, movement",
    externalUrl: "https://sarahjohnson.photo/urban-symphony",
    attributes: [
      { trait_type: "Location", value: "New York" },
      { trait_type: "Time", value: "Golden Hour" },
      { trait_type: "Style", value: "Street Photography" },
      { trait_type: "Mood", value: "Dynamic" },
    ],
  },
  {
    id: "3",
    title: "Ethereal Beats Vol. 1",
    slug: "ethereal-beats-vol-1",
    description:
      "An ambient electronic music composition that blends organic sounds with synthetic textures to create an otherworldly listening experience.",
    type: "Music",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Marcus Rodriguez",
    creator: creators[2],
    licenseType: "open-source",
    ipVersion: "2.0",
    registrationDate: "2024-01-13",
    timestamp: "1 day ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x3c4d5e6f7a8b",
    fileFormat: "WAV",
    commercialUse: true,
    modifications: true,
    attribution: true,
    tags: "music, ambient, electronic, experimental",
    externalUrl: "https://marcusrodriguez.music/ethereal-beats",
    attributes: [
      { trait_type: "Genre", value: "Ambient Electronic" },
      { trait_type: "Duration", value: "4:32" },
      { trait_type: "BPM", value: "85" },
      { trait_type: "Key", value: "C Minor" },
    ],
  },
  {
    id: "4",
    title: "Neural Network Visualization",
    slug: "neural-network-visualization",
    description:
      "An interactive data visualization showing the structure and flow of information through a deep learning neural network.",
    type: "Document",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Alex Chen",
    creator: creators[0],
    licenseType: "custom",
    ipVersion: "1.1",
    registrationDate: "2024-01-12",
    timestamp: "2 days ago",
    blockchain: "Starknet",
    protectionStatus: "Pending",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x4d5e6f7a8b9c",
    fileFormat: "SVG",
    commercialUse: true,
    modifications: false,
    attribution: true,
    tags: "data visualization, AI, neural networks, interactive",
    externalUrl: "https://alexchen.art/neural-viz",
    attributes: [
      { trait_type: "Type", value: "Interactive" },
      { trait_type: "Technology", value: "D3.js" },
      { trait_type: "Complexity", value: "High" },
      { trait_type: "Data Source", value: "TensorFlow" },
    ],
  },
]

export const collections: Collection[] = [
  {
    id: "1",
    name: "Quantum Series",
    slug: "quantum-series",
    description: "A collection exploring quantum physics through digital art",
    coverImage: "/placeholder.svg?height=300&width=400",
    creator: creators[0],
    assets: [timelineAssets[0]],
    totalAssets: 5,
    blockchain: "Starknet",
    floorPrice: "0.5 ETH",
    createdDate: "2024-01-10",
    tags: "quantum, physics, digital art",
  },
  {
    id: "2",
    name: "Urban Stories",
    slug: "urban-stories",
    description: "Street photography capturing city life moments",
    coverImage: "/placeholder.svg?height=300&width=400",
    creator: creators[1],
    assets: [timelineAssets[1]],
    totalAssets: 12,
    blockchain: "Starknet",
    floorPrice: "0.3 ETH",
    createdDate: "2024-01-08",
    tags: "photography, urban, street",
  },
]

export const portfolioAssets: AssetIP[] = [
  {
    id: "1",
    slug: "digital-sunset-dreams",
    title: "Digital Sunset Dreams",
    author: "Alex Chen",
    description: "A mesmerizing digital artwork capturing the essence of a perfect sunset.",
    type: "Art",
    mediaUrl: "/placeholder.svg?height=300&width=400",
    creator: creators[0],
    licenseType: "creative-commons",
    ipVersion: "1.2",
    commercialUse: false,
    modifications: true,
    attribution: true,
    registrationDate: "2024-01-15",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    timestamp: "2 hours ago",
    blockchain: "Starknet",
    contractAddress: "0x1234567890abcdef",
    tokenId: "1",
    tags: "digital-art, cyberpunk, sunset",
    externalUrl: "https://alexchen.art/digital-sunset-dreams",
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Style", value: "Cyberpunk" },
    ],
  },
  {
    id: "7",
    slug: "my-first-ip-creation",
    title: "My First IP Creation",
    author: "You",
    description: "A personal digital creation representing my journey into IP tokenization.",
    type: "Art",
    mediaUrl: "/placeholder.svg?height=300&width=400",
    creator: {
      id: "current-user",
      name: "You",
      username: "you",
      avatar: "/placeholder.svg?height=100&width=100",
      verified: false,
      bio: "New IP creator exploring blockchain technology",
      location: "Global",
      website: "",
      joinedDate: "2024-01-20",
      totalAssets: 1,
      totalCollections: 1,
      protectedAssets: 1,
    },
    licenseType: "all-rights",
    ipVersion: "1.0",
    commercialUse: false,
    modifications: false,
    attribution: true,
    registrationDate: "2024-01-20",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    timestamp: "1 day ago",
    blockchain: "Starknet",
    contractAddress: "0x9999000011112222",
    tokenId: "7",
    tags: "personal, first-creation, digital-art",
    externalUrl: "",
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Personal", value: "First Creation" },
    ],
  },
]

export const activities = [
  {
    id: "1",
    type: "mint",
    title: 'Minted "Abstract Thoughts"',
    description: "Successfully created and minted your digital artwork",
    timestamp: "2 hours ago",
    network: "Starknet",
    status: "completed",
    value: null,
    txHash: "0x1234...5678",
    assetId: "7",
  },
  {
    id: "2",
    type: "collection_create",
    title: 'Created "Personal Collection"',
    description: "New collection created to organize your IP assets",
    timestamp: "1 day ago",
    network: "Starknet",
    status: "completed",
    txHash: "0x2345...6789",
    collectionId: "personal-collection",
  },
  {
    id: "3",
    type: "transfer_in",
    title: 'Received "Digital Sunset Dreams"',
    description: "Asset transferred from 0x9876...4321",
    timestamp: "2 days ago",
    network: "Starknet",
    status: "completed",
    value: "0.5 ETH",
    txHash: "0x3456...7890",
    assetId: "1",
    fromAddress: "0x9876...4321",
  },
  {
    id: "4",
    type: "collection_add",
    title: 'Added asset to "Cyberpunk Landscapes"',
    description: "Digital Sunset Dreams added to collection",
    timestamp: "2 days ago",
    network: "Starknet",
    status: "completed",
    txHash: "0x4567...8901",
    assetId: "1",
    collectionId: "cyberpunk-landscapes",
  },
  {
    id: "5",
    type: "license",
    title: 'Licensed "Ambient Waves #1"',
    description: "Granted commercial license to 0x7777...3333",
    timestamp: "3 days ago",
    network: "Starknet",
    status: "completed",
    value: "0.2 ETH",
    txHash: "0x5678...9012",
    assetId: "3",
    toAddress: "0x7777...3333",
  },
]
