export const timelineAssets = [
  {
    id: "1",
    slug: "digital-sunset-dreams",
    name: "Digital Sunset Dreams",
    description:
      "A mesmerizing digital artwork capturing the essence of a perfect sunset over a cyberpunk cityscape. This piece represents the intersection of nature and technology.",
    image: "/placeholder.svg?height=400&width=600",
    external_url: "https://mip.app/asset/digital-sunset-dreams",
    animation_url: null,
    iptype: "Art",
    license: "CC BY-NC 4.0",
    creator: {
      id: "alex-chen",
      username: "alexchen",
      name: "Alex Chen",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      wallet: "0x1234...5678",
      bio: "Digital artist exploring the intersection of technology and nature",
      followers: 1250,
      following: 340,
      assets: 23,
    },
    timestamp: "2 hours ago",
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Style", value: "Cyberpunk" },
      { trait_type: "Medium", value: "Digital" },
      { trait_type: "Year", value: "2024" },
      { trait_type: "Resolution", value: "4K" },
    ],
    tags: ["digital-art", "cyberpunk", "sunset", "technology"],
  },
  {
    id: "2",
    slug: "quantum-poetry-collection",
    name: "Quantum Poetry Collection",
    description:
      "An experimental collection of poems exploring quantum mechanics through verse. Each poem is a unique interpretation of quantum phenomena.",
    image: "/placeholder.svg?height=400&width=600",
    external_url: "https://mip.app/asset/quantum-poetry-collection",
    animation_url: null,
    iptype: "Publications",
    license: "All Rights Reserved",
    creator: {
      id: "maya-rodriguez",
      username: "mayarodriguez",
      name: "Maya Rodriguez",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      wallet: "0x2345...6789",
      bio: "Poet and physicist merging science with literature",
      followers: 890,
      following: 156,
      assets: 12,
    },
    timestamp: "4 hours ago",
    attributes: [
      { trait_type: "Genre", value: "Poetry" },
      { trait_type: "Theme", value: "Science" },
      { trait_type: "Language", value: "English" },
      { trait_type: "Pages", value: "24" },
      { trait_type: "Format", value: "PDF" },
    ],
    tags: ["poetry", "quantum", "literature", "science"],
  },
  {
    id: "3",
    slug: "ambient-waves-1",
    name: "Ambient Waves #1",
    description:
      "A 10-minute ambient composition featuring synthesized ocean waves and ethereal melodies. Perfect for meditation and relaxation.",
    image: "/placeholder.svg?height=400&width=600",
    external_url: "https://mip.app/asset/ambient-waves-1",
    animation_url: "https://example.com/audio/ambient-waves.mp3",
    iptype: "Audio",
    license: "CC BY-SA 4.0",
    creator: {
      id: "sound-collective",
      username: "soundcollective",
      name: "Sound Collective",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: false,
      wallet: "0x3456...7890",
      bio: "Experimental music collective creating ambient soundscapes",
      followers: 2100,
      following: 89,
      assets: 45,
    },
    timestamp: "6 hours ago",
    attributes: [
      { trait_type: "Duration", value: "10:32" },
      { trait_type: "Genre", value: "Ambient" },
      { trait_type: "BPM", value: "60" },
      { trait_type: "Key", value: "C Major" },
      { trait_type: "Format", value: "MP3" },
    ],
    tags: ["ambient", "music", "meditation", "waves"],
  },
  {
    id: "4",
    slug: "smart-contract-audit-tool",
    name: "Smart Contract Audit Tool",
    description:
      "An automated tool for auditing smart contracts on Starknet. Includes vulnerability detection and gas optimization suggestions.",
    image: "/placeholder.svg?height=400&width=600",
    external_url: "https://github.com/example/audit-tool",
    animation_url: null,
    iptype: "Software",
    license: "MIT License",
    creator: {
      id: "dr-sarah-kim",
      username: "drsarahkim",
      name: "Dr. Sarah Kim",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      wallet: "0x4567...8901",
      bio: "Blockchain security researcher and smart contract auditor",
      followers: 3400,
      following: 234,
      assets: 8,
    },
    timestamp: "8 hours ago",
    attributes: [
      { trait_type: "Language", value: "Python" },
      { trait_type: "Framework", value: "Cairo" },
      { trait_type: "Version", value: "1.0.0" },
      { trait_type: "License Type", value: "Open Source" },
      { trait_type: "Platform", value: "Starknet" },
    ],
    tags: ["software", "audit", "smart-contracts", "security"],
  },
  {
    id: "5",
    slug: "renewable-energy-patent",
    name: "Renewable Energy Patent",
    description:
      "A novel solar panel design that increases efficiency by 30% through innovative light-capturing technology.",
    image: "/placeholder.svg?height=400&width=600",
    external_url: "https://patents.uspto.gov/example",
    animation_url: null,
    iptype: "Patents",
    license: "Patent Protected",
    creator: {
      id: "greentech-innovations",
      username: "greentechinnovations",
      name: "GreenTech Innovations",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
      wallet: "0x5678...9012",
      bio: "Leading renewable energy research and development company",
      followers: 5600,
      following: 78,
      assets: 15,
    },
    timestamp: "12 hours ago",
    attributes: [
      { trait_type: "Patent Number", value: "US11234567" },
      { trait_type: "Filing Date", value: "2024-01-15" },
      { trait_type: "Technology", value: "Solar Energy" },
      { trait_type: "Efficiency Gain", value: "30%" },
      { trait_type: "Status", value: "Granted" },
    ],
    tags: ["patent", "solar", "renewable-energy", "innovation"],
  },
]

export const portfolioAssets = [
  {
    id: "1",
    slug: "digital-sunset-dreams",
    name: "Digital Sunset Dreams",
    description: "A mesmerizing digital artwork capturing the essence of a perfect sunset.",
    image: "/placeholder.svg?height=300&width=400",
    iptype: "Art",
    license: "CC BY-NC 4.0",
    status: "owned",
    creator: {
      id: "alex-chen",
      username: "alexchen",
      name: "Alex Chen",
    },
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Style", value: "Cyberpunk" },
    ],
  },
  {
    id: "2",
    slug: "my-first-ip-creation",
    name: "My First IP Creation",
    description: "A personal digital creation representing my journey into IP tokenization.",
    image: "/placeholder.svg?height=300&width=400",
    iptype: "Art",
    license: "All Rights Reserved",
    status: "created",
    creator: {
      id: "current-user",
      username: "you",
      name: "You",
    },
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Personal", value: "First Creation" },
    ],
  },
]

export const activities = [
  {
    id: "1",
    type: "mint",
    title: 'Minted "Abstract Thoughts"',
    description: "Successfully created and minted your digital artwork",
    timestamp: "2 hours ago",
    network: "Starknet",
    status: "completed",
    value: null,
    txHash: "0x1234...5678",
  },
  {
    id: "2",
    type: "transfer_in",
    title: 'Received "Digital Sunset Dreams"',
    description: "Asset transferred from 0x9876...4321",
    timestamp: "1 day ago",
    network: "Starknet",
    status: "completed",
    value: "0.5 ETH",
    txHash: "0x2345...6789",
  },
  {
    id: "3",
    type: "sale",
    title: 'Sold "My First Creation"',
    description: "Asset sold to collector 0x5555...1111",
    timestamp: "2 days ago",
    network: "Starknet",
    status: "completed",
    value: "0.8 ETH",
    txHash: "0x3456...7890",
  },
  {
    id: "4",
    type: "mint",
    title: 'Minted "Poetry Collection #1"',
    description: "Created your first literary NFT",
    timestamp: "3 days ago",
    network: "Starknet",
    status: "completed",
    value: null,
    txHash: "0x4567...8901",
  },
  {
    id: "5",
    type: "transfer_out",
    title: 'Sent "Music Track #5"',
    description: "Transferred to 0x7777...3333",
    timestamp: "5 days ago",
    network: "Starknet",
    status: "completed",
    value: null,
    txHash: "0x5678...9012",
  },
]

// Mock creators data
export const creators = [
  {
    id: "alex-chen",
    username: "alexchen",
    name: "Alex Chen",
    avatar: "/placeholder.svg?height=120&width=120",
    banner: "/placeholder.svg?height=200&width=600",
    verified: true,
    wallet: "0x1234...5678",
    bio: "Digital artist exploring the intersection of technology and nature. Creating immersive experiences that bridge the gap between the physical and digital worlds.",
    location: "San Francisco, CA",
    website: "https://alexchen.art",
    twitter: "@alexchen_art",
    instagram: "@alexchen.digital",
    followers: 1250,
    following: 340,
    assets: 23,
    joined: "March 2023",
    totalViews: 45600,
    totalLikes: 3200,
  },
  {
    id: "maya-rodriguez",
    username: "mayarodriguez",
    name: "Maya Rodriguez",
    avatar: "/placeholder.svg?height=120&width=120",
    banner: "/placeholder.svg?height=200&width=600",
    verified: true,
    wallet: "0x2345...6789",
    bio: "Poet and physicist merging science with literature. Exploring the quantum realm through verse and creating bridges between complex scientific concepts and human emotion.",
    location: "Barcelona, Spain",
    website: "https://mayarodriguez.com",
    twitter: "@maya_quantum",
    instagram: "@maya.poetry",
    followers: 890,
    following: 156,
    assets: 12,
    joined: "January 2023",
    totalViews: 23400,
    totalLikes: 1800,
  },
]
