import type { AssetIP, Creator, Collection } from "@/src/types/asset"

export const creators: Creator[] = [
  {
    id: "1",
    name: "Alex Chen",
    username: "alexchen",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: true,
    bio: "Digital artist and IP creator specializing in generative art and blockchain technology.",
    location: "San Francisco, CA",
    website: "https://alexchen.art",
    joined: "2023-01-15",
    assets: 24,
    collections: 3,
    followers: 1250,
    following: 340,
    wallet: "0x19eefbfa551b6d772d4084946fedd4037c0935968a74d60d54e11ffdaa4d99c",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    username: "sarahjohnson",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: true,
    bio: "Photographer and visual storyteller with a passion for capturing authentic moments.",
    location: "New York, NY",
    website: "https://sarahjohnson.photo",
    joined: "2023-02-20",
    assets: 18,
    collections: 2,
    followers: 890,
    following: 220,
    wallet: "0x2222222222222222222222222222222222222222",
  },
  {
    id: "3",
    name: "Marcus Rodriguez",
    username: "marcusrodriguez",
    avatar: "/placeholder.svg?height=100&width=100",
    verified: false,
    bio: "Music producer and sound designer creating innovative audio experiences.",
    location: "Los Angeles, CA",
    website: "https://marcusrodriguez.music",
    joined: "2023-03-10",
    assets: 12,
    collections: 1,
    followers: 567,
    following: 180,
    wallet: "0x3333333333333333333333333333333333333333",
  },
]

export const timelineAssets: AssetIP[] = [
  {
    id: "1",
    title: "Quantum Dreams #001",
    slug: "quantum-dreams-001",
    description:
      "A mesmerizing digital artwork exploring the intersection of quantum physics and consciousness through vibrant colors and geometric patterns.",
    type: "Art",
    template: "art",
    collection: "Quantum Series",
    collectionSlug: "quantum-series",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Alex Chen",
    creator: {
      id: creators[0].id,
      username: creators[0].username,
      name: creators[0].name,
      avatar: creators[0].avatar,
      verified: creators[0].verified,
      wallet: creators[0].wallet,
      bio: creators[0].bio,
      followers: creators[0].followers,
      following: creators[0].following,
      assets: creators[0].assets,
    },
    licenseType: "creative-commons",
    licenseDetails: "CC BY-SA 4.0",
    ipVersion: "1.0",
    registrationDate: "2024-01-15",
    timestamp: "2 hours ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x1a2b3c4d5e6f",
    fileFormat: "PNG",
    commercialUse: true,
    modifications: true,
    attribution: true,
    tags: "digital art, quantum, consciousness, geometric",
    externalUrl: "https://quantum-dreams.art",
    attributes: [
      { trait_type: "Style", value: "Abstract" },
      { trait_type: "Color Palette", value: "Vibrant" },
      { trait_type: "Complexity", value: "High" },
      { trait_type: "Medium", value: "Digital" },
    ],
  },
  {
    id: "2",
    title: "Urban Symphony",
    slug: "urban-symphony",
    description:
      "A captivating photograph capturing the rhythm and energy of city life through architectural lines and human movement.",
    type: "Image",
    template: "image",
    collection: "Urban Stories",
    collectionSlug: "urban-stories",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Sarah Johnson",
    creator: {
      id: creators[1].id,
      username: creators[1].username,
      name: creators[1].name,
      avatar: creators[1].avatar,
      verified: creators[1].verified,
      wallet: creators[1].wallet,
      bio: creators[1].bio,
      followers: creators[1].followers,
      following: creators[1].following,
      assets: creators[1].assets,
    },
    licenseType: "all-rights",
    licenseDetails: "All rights reserved",
    ipVersion: "1.2",
    registrationDate: "2024-01-14",
    timestamp: "5 hours ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x2b3c4d5e6f7a",
    fileFormat: "JPEG",
    commercialUse: false,
    modifications: false,
    attribution: true,
    tags: "photography, urban, architecture, movement",
    externalUrl: "https://sarahjohnson.photo/urban-symphony",
    attributes: [
      { trait_type: "Location", value: "New York" },
      { trait_type: "Time", value: "Golden Hour" },
      { trait_type: "Style", value: "Street Photography" },
      { trait_type: "Mood", value: "Dynamic" },
    ],
  },
  {
    id: "3",
    title: "Ethereal Beats Vol. 1",
    slug: "ethereal-beats-vol-1",
    description:
      "An ambient electronic music composition that blends organic sounds with synthetic textures to create an otherworldly listening experience.",
    type: "Music",
    template: "audio",
    collection: "Ambient Soundscapes",
    collectionSlug: "ambient-soundscapes",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Marcus Rodriguez",
    creator: {
      id: creators[2].id,
      username: creators[2].username,
      name: creators[2].name,
      avatar: creators[2].avatar,
      verified: creators[2].verified,
      wallet: creators[2].wallet,
      bio: creators[2].bio,
      followers: creators[2].followers,
      following: creators[2].following,
      assets: creators[2].assets,
    },
    licenseType: "open-source",
    licenseDetails: "MIT License",
    ipVersion: "2.0",
    registrationDate: "2024-01-13",
    timestamp: "1 day ago",
    blockchain: "Starknet",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x3c4d5e6f7a8b",
    fileFormat: "WAV",
    commercialUse: true,
    modifications: true,
    attribution: true,
    tags: "music, ambient, electronic, experimental",
    externalUrl: "https://marcusrodriguez.music/ethereal-beats",
    attributes: [
      { trait_type: "Genre", value: "Ambient Electronic" },
      { trait_type: "Duration", value: "4:32" },
      { trait_type: "BPM", value: "85" },
      { trait_type: "Key", value: "C Minor" },
    ],
  },
  {
    id: "4",
    title: "Neural Network Visualization",
    slug: "neural-network-visualization",
    description:
      "An interactive data visualization showing the structure and flow of information through a deep learning neural network.",
    type: "Document",
    template: "document",
    collection: "AI Research Papers",
    collectionSlug: "ai-research-papers",
    mediaUrl: "/placeholder.svg?height=400&width=600",
    author: "Alex Chen",
    creator: {
      id: creators[0].id,
      username: creators[0].username,
      name: creators[0].name,
      avatar: creators[0].avatar,
      verified: creators[0].verified,
      wallet: creators[0].wallet,
      bio: creators[0].bio,
      followers: creators[0].followers,
      following: creators[0].following,
      assets: creators[0].assets,
    },
    licenseType: "custom",
    licenseDetails: "Academic use only",
    ipVersion: "1.1",
    registrationDate: "2024-01-12",
    timestamp: "2 days ago",
    blockchain: "Starknet",
    protectionStatus: "Pending",
    protectionScope: "Global",
    protectionDuration: "70 years",
    tokenId: "0x4d5e6f7a8b9c",
    fileFormat: "SVG",
    commercialUse: true,
    modifications: false,
    attribution: true,
    tags: "data visualization, AI, neural networks, interactive",
    externalUrl: "https://alexchen.art/neural-viz",
    attributes: [
      { trait_type: "Type", value: "Interactive" },
      { trait_type: "Technology", value: "D3.js" },
      { trait_type: "Complexity", value: "High" },
      { trait_type: "Data Source", value: "TensorFlow" },
    ],
  },
]

export const collections: Collection[] = [
  {
    id: "1",
    name: "Quantum Series",
    slug: "quantum-series",
    description: "A collection exploring quantum physics through digital art",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[0].id,
      username: creators[0].username,
      name: creators[0].name,
      avatar: creators[0].avatar,
      verified: creators[0].verified,
      wallet: creators[0].wallet
    },
    assets: 5,
    blockchain: "Starknet",
    floorPrice: "0.5 ETH",
    totalVolume: "2.5 ETH",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-15T12:30:00Z",
    category: "digital art",
    tags: "quantum, physics, digital art",
    isPublic: true,
    isFeatured: true,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  },
  {
    id: "2",
    name: "Urban Stories",
    slug: "urban-stories",
    description: "Street photography capturing city life moments",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[1].id,
      username: creators[1].username,
      name: creators[1].name,
      avatar: creators[1].avatar,
      verified: creators[1].verified,
      wallet: creators[1].wallet
    },
    assets: 12,
    blockchain: "Starknet",
    floorPrice: "0.3 ETH",
    totalVolume: "4.2 ETH",
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-14T08:15:00Z",
    category: "photography",
    tags: "photography, urban, street",
    isPublic: true,
    isFeatured: false,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  },
  {
    id: "3",
    name: "Ambient Soundscapes",
    slug: "ambient-soundscapes",
    description: "Ethereal electronic music compositions for meditation and focus",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[2].id,
      username: creators[2].username,
      name: creators[2].name,
      avatar: creators[2].avatar,
      verified: creators[2].verified,
      wallet: creators[2].wallet
    },
    assets: 8,
    blockchain: "Starknet",
    floorPrice: "0.2 ETH",
    totalVolume: "1.6 ETH",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-13T16:45:00Z",
    category: "audio",
    tags: "music, ambient, electronic, experimental",
    isPublic: true,
    isFeatured: true,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  },
  {
    id: "4",
    name: "AI Research Papers",
    slug: "ai-research-papers",
    description: "Groundbreaking research in artificial intelligence and machine learning",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[0].id,
      username: creators[0].username,
      name: creators[0].name,
      avatar: creators[0].avatar,
      verified: creators[0].verified,
      wallet: creators[0].wallet
    },
    assets: 15,
    blockchain: "Starknet",
    floorPrice: "0.8 ETH",
    totalVolume: "12.0 ETH",
    createdAt: "2023-12-20T00:00:00Z",
    updatedAt: "2024-01-16T14:20:00Z",
    category: "publications",
    tags: "AI, research, machine learning, neural networks",
    isPublic: true,
    isFeatured: false,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  },
  {
    id: "5",
    name: "Blockchain Patents",
    slug: "blockchain-patents",
    description: "Innovative patent applications for blockchain and distributed systems",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[1].id,
      username: creators[1].username,
      name: creators[1].name,
      avatar: creators[1].avatar,
      verified: creators[1].verified,
      wallet: creators[1].wallet
    },
    assets: 6,
    blockchain: "Starknet",
    floorPrice: "1.2 ETH",
    totalVolume: "7.2 ETH",
    createdAt: "2023-11-15T00:00:00Z",
    updatedAt: "2024-01-10T10:30:00Z",
    category: "patents",
    tags: "blockchain, patents, distributed systems, innovation",
    isPublic: false,
    isFeatured: false,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  },
  {
    id: "6",
    name: "AI Art Experiments",
    slug: "ai-art-experiments",
    description: "Cutting-edge AI-generated artworks pushing creative boundaries",
    coverImage: "/placeholder.svg?height=300&width=400",
    bannerImage: "/placeholder.svg?height=200&width=800",
    creator: {
      id: creators[2].id,
      username: creators[2].username,
      name: creators[2].name,
      avatar: creators[2].avatar,
      verified: creators[2].verified,
      wallet: creators[2].wallet
    },
    assets: 20,
    blockchain: "Starknet",
    floorPrice: "0.4 ETH",
    totalVolume: "8.0 ETH",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-17T09:15:00Z",
    category: "ai art",
    tags: "AI, generative art, machine learning, creativity",
    isPublic: true,
    isFeatured: true,
    contractAddress: "0x04b67deb64d285d3de684246084e74ad25d459989b7336786886ec63a28e0cd4"
  }
]

export const portfolioAssets: AssetIP[] = [
  {
    id: "1",
    slug: "digital-sunset-dreams",
    title: "Digital Sunset Dreams",
    author: "Alex Chen",
    description: "A mesmerizing digital artwork capturing the essence of a perfect sunset.",
    type: "Art",
    template: "art",
    collection: "Quantum Series",
    collectionSlug: "quantum-series",
    mediaUrl: "/placeholder.svg?height=300&width=400",
    creator: {
      id: creators[0].id,
      username: creators[0].username,
      name: creators[0].name,
      avatar: creators[0].avatar,
      verified: creators[0].verified,
      wallet: creators[0].wallet,
      bio: creators[0].bio,
      followers: creators[0].followers,
      following: creators[0].following,
      assets: creators[0].assets,
    },
    licenseType: "creative-commons",
    licenseDetails: "CC BY-SA 4.0",
    ipVersion: "1.2",
    commercialUse: false,
    modifications: true,
    attribution: true,
    registrationDate: "2024-01-15",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    timestamp: "2 hours ago",
    blockchain: "Starknet",
    contractAddress: "0x1234567890abcdef",
    tokenId: "1",
    tags: "digital-art, cyberpunk, sunset",
    externalUrl: "https://alexchen.art/digital-sunset-dreams",
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Style", value: "Cyberpunk" },
    ],
  },
  {
    id: "7",
    slug: "my-first-ip-creation",
    title: "My First IP Creation",
    author: "You",
    description: "A personal digital creation representing my journey into IP tokenization.",
    type: "Art",
    template: "art",
    collection: "Personal Collection",
    collectionSlug: "personal-collection",
    mediaUrl: "/placeholder.svg?height=300&width=400",
    creator: {
      id: "current-user",
      name: "You",
      username: "you",
      avatar: "/placeholder.svg?height=100&width=100",
      verified: false,
      wallet: "0x9999000011112222",
      bio: "New IP creator exploring blockchain technology",
      followers: 0,
      following: 5,
      assets: 1,
    },
    licenseType: "all-rights",
    licenseDetails: "All rights reserved",
    ipVersion: "1.0",
    commercialUse: false,
    modifications: false,
    attribution: true,
    registrationDate: "2024-01-20",
    protectionStatus: "Protected",
    protectionScope: "Global",
    protectionDuration: "70 years",
    timestamp: "1 day ago",
    blockchain: "Starknet",
    contractAddress: "0x9999000011112222",
    tokenId: "7",
    tags: "personal, first-creation, digital-art",
    externalUrl: "",
    attributes: [
      { trait_type: "Category", value: "Digital Art" },
      { trait_type: "Personal", value: "First Creation" },
    ],
  },
]

export const activities = [
  {
    id: "1",
    type: "mint" as const,
    title: 'Minted "Abstract Thoughts"',
    description: "Successfully created and minted your digital artwork",
    timestamp: "2 hours ago",
    network: "Starknet",
    status: "completed" as const,
    value: undefined,
    txHash: "0x1234...5678",
    assetId: "7",
  },
  {
    id: "2",
    type: "collection_create" as const,
    title: 'Created "Personal Collection"',
    description: "New collection created to organize your IP assets",
    timestamp: "1 day ago",
    network: "Starknet",
    status: "completed" as const,
    txHash: "0x2345...6789",
    collectionId: "personal-collection",
  },
  {
    id: "3",
    type: "transfer_in" as const,
    title: 'Received "Digital Sunset Dreams"',
    description: "Asset transferred from 0x9876...4321",
    timestamp: "2 days ago",
    network: "Starknet",
    status: "completed" as const,
    value: "0.5 ETH",
    txHash: "0x3456...7890",
    assetId: "1",
    fromAddress: "0x9876...4321",
  },
  {
    id: "4",
    type: "collection_add" as const,
    title: 'Added asset to "Cyberpunk Landscapes"',
    description: "Digital Sunset Dreams added to collection",
    timestamp: "2 days ago",
    network: "Starknet",
    status: "completed" as const,
    txHash: "0x4567...8901",
    assetId: "1",
    collectionId: "cyberpunk-landscapes",
  },
  {
    id: "5",
    type: "license" as const,
    title: 'Licensed "Ambient Waves #1"',
    description: "Granted commercial license to 0x7777...3333",
    timestamp: "3 days ago",
    network: "Starknet",
    status: "completed" as const,
    value: "0.2 ETH",
    txHash: "0x5678...9012",
    assetId: "3",
    toAddress: "0x7777...3333",
  },
]
